title: Fraud Detection Platform

description: >-
  An end-to-end machine learning platform for detecting
  fraudulent transactions in real-time.

url: "https://sobhanalizadeh.github.io"
baseurl: "/Fraud-Detection-Platform"

theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: Sobhan Alizadeh

social:
  github: sobhanalizadeh
  
author: Sobhan Alizadeh

lang: en
